
replicaCount: 1

image:
  repository: maximleus/hostinfo
  tag: latest
  pullPolicy: Always



service:
  # type: LoadBalancer
  # type: NodePort
  type: ClusterIP
  port: 8080
  targetPort: 8080
  # nodePort: 31001

health_check:
  readinessProbe:
    path: /healthz/ready
  livenessProbe:
    path: /healthz/live


envs:  
  HOSTINFO_PORT: 8080
  HOSTINFO_ADDR: "0.0.0.0"
  HOSTINFO_DEBUG: false


